package export

import (
	"fmt"
	"strings"

	"github.com/kyanite/prism/internal/palette"
)

// ExportCSS exports palette as CSS custom properties
func ExportCSS(p palette.Palette) string {
	// Format: CSS variables with both hex and RGB values

	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("/* Generated by prism.sh - %s */\n", p.Name))
	sb.WriteString(fmt.Sprintf("/* Created: %s */\n", p.CreatedAt.Format("2006-01-02T15:04:05Z07:00")))
	sb.WriteString(fmt.Sprintf("/* Harmony: %s */\n\n", p.HarmonyRule))

	sb.WriteString(":root {\n")
	sb.WriteString("  /* Hex values */\n")

	for i, c := range p.Colors {
		role := getRoleName(i)
		sb.WriteString(fmt.Sprintf("  --color-%s: %s;\n", role, c.Hex))
	}

	sb.WriteString("\n  /* RGB values (for alpha channel) */\n")
	for i, c := range p.Colors {
		role := getRoleName(i)
		sb.WriteString(fmt.Sprintf("  --color-%s-rgb: %d, %d, %d;\n", role, c.RGB.R, c.RGB.G, c.RGB.B))
	}

	sb.WriteString("}\n")

	return sb.String()
}

// getRoleName returns semantic role name for color index
func getRoleName(index int) string {
	roles := []string{"primary", "secondary", "accent", "background", "text", "success", "warning"}
	if index < len(roles) {
		return roles[index]
	}
	return fmt.Sprintf("color-%d", index+1)
}
