package export

import (
	"fmt"
	"strings"

	"github.com/kyanite/prism/internal/palette"
)

// ExportTOML exports palette to TOML format
func ExportTOML(p palette.Palette) string {
	// TODO: Implement TOML export per PRD specification

	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("# Generated by prism.sh - %s\n", p.Name))
	sb.WriteString(fmt.Sprintf("name = \"%s\"\n", p.Name))
	sb.WriteString(fmt.Sprintf("harmony_rule = \"%s\"\n", p.HarmonyRule))
	sb.WriteString(fmt.Sprintf("created_at = \"%s\"\n\n", p.CreatedAt.Format("2006-01-02T15:04:05Z07:00")))

	for i, c := range p.Colors {
		sb.WriteString("[[colors]]\n")
		if c.Name != "" {
			sb.WriteString(fmt.Sprintf("name = \"%s\"\n", c.Name))
		} else {
			sb.WriteString(fmt.Sprintf("name = \"Color %d\"\n", i+1))
		}
		sb.WriteString(fmt.Sprintf("hex = \"%s\"\n", c.Hex))
		sb.WriteString(fmt.Sprintf("role = \"%s\"\n\n", getRoleName(i)))
	}

	return sb.String()
}
